export enum statusDaFaseDeGerenciamentoDT {
  IDENTIFICACAO = 'IDENTIFICACAO',
  MENSURACAO = 'MENSURACAO',
  PRIORIZACAO = 'PRIORIZACAO',
  REEMBOLSO = 'REEMBOLSO',
  MONITORAMENTO = 'MONITORAMENTO'
}